### ISSUE TITLE
Server error when opening portfolio project

### ISSUE THREAD

**Issue by ZoranPandovski** [able-bio/suggestion-box#10]
**Describe the bug**
I have created a test project for my portfolio. When I try to open it server error is thrown.
Link https://able.bio/ZoranPandovski/portfolio

**To Reproduce**
1. Go to https://able.bio/ZoranPandovski/portfolio
2. Click on  test

**Comment by RhettTrickett** [comment]
Thanks for reporting! This should be fixed now.

**Comment by ZoranPandovski** [comment]
It's working now. Thanks, @RhettTrickett
