### ISSUE TITLE
There is no such page error

### ISSUE THREAD

**Issue by ZoranPandovski** [able-bio/suggestion-box#11]
**Describe the bug**
On creating a new post, there is no such page error is returned.

**To Reproduce**
1. Click on 'New Post'
2. See error 'There is no such page'

**Screenshots**
![Screenshot from 2019-08-07 11-10-03](https://user-images.githubusercontent.com/7192539/62610516-1f70ba80-b904-11e9-8631-8c515dfede3d.png)

**Comment by RhettTrickett** [comment]
@ZoranPandovski where did you see the New Post button? That should be hidden as it's part of the new article editor we are building.

**Comment by ZoranPandovski** [comment]
It is on the right top, next to the user section.
![Screenshot from 2019-08-08 10-46-55](https://user-images.githubusercontent.com/7192539/62688824-ea2ea000-b9c9-11e9-8925-02a765217387.png)

**Comment by RhettTrickett** [comment]
Thanks @ZoranPandovski - have patched so that it's no longer visible.

![094](https://user-images.githubusercontent.com/2250831/62702157-e9076e00-b9dd-11e9-87e2-e566a431549d.gif)
