### ISSUE TITLE
Editor: Upload image file picker is missing

### ISSUE THREAD

**Issue by ZoranPandovski** [able-bio/suggestion-box#12]
**Describe the bug**
When you try to insert an image, there is no option to select the file with file picker.

**To Reproduce**
1. Go to Create a new article
2. Insert new image
3. There is no file picker option

**Expected behavior**
Users should be able to select local files.

**Screenshots**
![Screenshot from 2019-09-25 20-12-11](https://user-images.githubusercontent.com/7192539/65628120-19788b00-dfd1-11e9-9884-7aeb6ee94f62.png)

**Comment by RhettTrickett** [comment]
Hey @ZoranPandovski - you can drag and drop images into the editor to upload them. But I'll make a note for us to add the above functionality so that mobile users can upload images too.

**Comment by ZoranPandovski** [comment]
Thanks @RhettTrickett , I didn't notice that :D Yes, for some users it will be confusing without file picker, or you can add a tooltip that explains drag and drop upload.

**Comment by Minenash** [comment]
For now, you can post it to a service like imgur, and put the link in the location spot.

**Comment by RhettTrickett** [comment]
+1 from @Minenash

**Comment by drenther** [comment]
@Minenash @ZoranPandovski You can also directly drag and drop an image on the editor writing space.

Update: I see it was already mentioned. We are working on making these actions more obvious, with tips and shorthand guides.

**Comment by drenther** [comment]
We are working on making these actions more obvious, with tips and shorthand guides.

**Comment by RhettTrickett** [comment]
@ZoranPandovski @Minenash - this has been fixed by an update from @drenther this week.
