### ISSUE TITLE
Create table option is missing

### ISSUE THREAD

**Issue by ZoranPandovski** [able-bio/suggestion-box#13]
I am not sure how to create a table? Is that still not implemented or I am not able to find that option ?

**Comment by RhettTrickett** [comment]
Hi @ZoranPandovski - tables can be supported but we just need to configure the UI to allow you to create them. Right now even if you try to do it using markdown syntax the characters get escaped. We'll add support for this pretty soon and update here when it's ready.

**Comment by RhettTrickett** [comment]
This is now available in the editor.
