### ISSUE TITLE
User website link icon

### ISSUE THREAD

**Issue by Minenash** [able-bio/suggestion-box#15]
I think using the standard web icon, 🌐, would better represent that the icon links to the user's site, than the current link icon, 🔗. Also the icon doesn't appear in the user card underneath articles.

**Comment by RhettTrickett** [comment]
Will consider this. I'm working on some ideas to show the domain instead so that users can promote their own website / blog domain on Able instead of it being hidden behind an icon.

**Comment by RhettTrickett** [comment]
Closing this ticket for now as this will be incorporated with the user profile revamp project coming up.
