### ISSUE TITLE
Doesn't work Follow button

### ISSUE THREAD

**Issue by mjablecnik** [able-bio/suggestion-box#2]
**Describe the bug**
Doesn't work Follow button.

**To Reproduce**
1. Go to profile any user
2. Click on Follow button
3. I don't see any response or works.

**Expected behavior**
I want see somewhere my following users and follow their articles.

**Desktop (please complete the following information):**
 - Browser: Firefox Quantum 63.0.3
 - System: Linux Mint 19

**Comment by RhettTrickett** [comment]
Thanks for raising this Martin.

I'll look into why the Follow button isn't working. Should have it resolved before the end of the weekend. Will also think about where might be a good place to manage followers.

Thanks for your feedback! If you have any more ideas, please do share them!

**Comment by RhettTrickett** [comment]
@Applemann This has now been fixed. Apologies for the delay. You can now also see your followers and people you follow in the top left corner of the home page (https://able.bio)
