### ISSUE TITLE
Previous article

### ISSUE THREAD

**Issue by RhettTrickett** [able-bio/suggestion-box#23]
_At one point there was an option to give a previous article. Why was it removed, and can we expect to see it again?_

@Minenash could you clarify what you meant by this? Not sure I understand. Thanks.

**Comment by Minenash** [comment]
If I remember correctly, it an option along with "add subheading", "add tags", etc, that would point to the previous article in a series.

**Comment by Minenash** [comment]
I think it's safe to close this

**Comment by Minenash** [comment]
I think this can safely be closed

**Comment by RhettTrickett** [comment]
I actually want to keep this open as it does feel like we need a link to your posts from the editor. I have an idea that I want to discuss with @drenther about this.
