### ISSUE TITLE
Ability to keep `Last name` blank

### ISSUE THREAD

**Issue by Minenash** [able-bio/suggestion-box#28]
My online presence is this username, and as I signed up with GitHub, it only took it as my first name. Because I could not keep the last name field empty, I was unable to change my bio. I eventually found a way around this by using an invisable non-space Unicode character, that allowed the form to submit successfully, but wasn't stored in the database.

I guess this is also a bug report for fields that can be submitted, but aren't stored.

**Comment by RhettTrickett** [comment]
We don't actually require a first and last name in the database. It was just some legacy frontend validation that has now been removed. If you don't have a first and or last name it will just display your username instead.
