### ISSUE TITLE
Some link for view or create new issues

### ISSUE THREAD

**Issue by mjablecnik** [able-bio/suggestion-box#3]
I thing that somewhere on the Able.bio page  should be some button or link for easy find where I can create issue when I find any bug.
And this suggestion-box for issues will be more used..
This able-bio project I was founding a long time here on github.

**Comment by RhettTrickett** [comment]
Good idea Martin, will look into adding something this weekend!

**Comment by RhettTrickett** [comment]
This has now been added and can be viewied in the right hand column of the Able newsfeed (home screen).
