### ISSUE TITLE
Ability to have a strictly chronological feed

### ISSUE THREAD

**Issue by Minenash** [able-bio/suggestion-box#32]

**Comment by drenther** [comment]
Noted. We will look into it soon.

**Comment by RhettTrickett** [comment]
@Minenash I've added some filters to the top of the newsfeed. Let me know what you think.

**Comment by Minenash** [comment]
Awesome, It looks great! Though it would be nice to be able to set a default. So `Feed`'s url would change to `https://able.bio/?order=feed` (or `default`), the `Interests` tab could be renamed to `Feed` or `Newsfeed`, and have the default sort option above the interest selection.

**Comment by RhettTrickett** [comment]
Okay, I've made a change so that your last selected feed order is remembered. So whenever you load up the newsfeed now it should remember your preference.

Happy New Year btw!

**Comment by Minenash** [comment]
Happy New Year to you too!

Out of curiosity is the last loaded stored on the client side or server side?

**Comment by RhettTrickett** [comment]
It’s stored server-side against your session.
