### ISSUE TITLE
Link based on the title of when it was first saved, not when first published

### ISSUE THREAD

**Issue by Minenash** [able-bio/suggestion-box#33]
**Describe the bug**
When writting a post, the link is based on the title as it was when it was first saved, leading to a situation where the title no longer matches the link

**To Reproduce**
1. Write a post with a title.
2. Save post
3. Change title
4. Publish
5. Look at link

**Expected behavior**
I expected either of the following:
* The link would change when the title changed
* The title part of the link would be independent of the id. (i.e. it doesn't matter what the title part of it is, or even if it there at all, as long as the id is correct

**Comment by drenther** [comment]
Thanks for the detailed Issue Description. I think I agree with the points made and a lot of other content systems have a similar approach. We will look into what solution works for us in this case.

**Comment by RhettTrickett** [comment]
This has been fixed. The URL will now change if you update the post title. We actually look up the post based on the id at the end of the URL so this way it won't break previous links that have been shared.

**Comment by Minenash** [comment]
Awesome! Could it also be made so, you don't _need_ text to work, so just able.bio/user/95378?

**Comment by RhettTrickett** [comment]
We could look at that but what is the point of it?

**Comment by Minenash** [comment]
* Shorter Links when needed
* If someone is copying an old link, they don't have to manually update the text (if they want the link to bit make sense)
