### ISSUE TITLE
Show subtitles on feed cards

### ISSUE THREAD

**Issue by Minenash** [able-bio/suggestion-box#34]
They show up on the cards on the post list of someones profile, but not on the main feed.

**Comment by drenther** [comment]
Agreed. @RhettTrickett - Let's discuss about this

**Comment by RhettTrickett** [comment]
Yeah, so the whole point of the newsfeed redesign was to make things extremely clean and remove as much noise as possible. We can look at some designs though to see if we can re-introduce without making things too noisy. Let's discuss.

**Comment by Minenash** [comment]
It definitely would make subtitles useful for people who use their feed, and it would make it more consistent.

For the design, we could add the text in the style of what the profile pages. Also while we're at it we could add the post read time next to the data, and the views next to the comments. It may make add some "noice" I feel like it would improve the expertise by a good about. For example, if you're checking you're feed on your phone waiting for something irl, wouldn't it be nice to know how long an article is, so you know if you can read it in time, without having to click in it.

Edit: Personally the best screen of the site visually, is the profile page. If we didn't have to worry about saying who wrote it, and have their picture with it, I would have suggested you used the same card.

**Comment by RhettTrickett** [comment]
I've played around with a few options, starting with what you've suggested. It seemed a bit strange to have the read time down in the bottom actions row (this is where Upvotes and other interactive data summaries will be displayed). So I tried adding it to the top row, after the date. However, it seemed like read time might be more helpful than the date (which you only really want to check for reference in some cases).

So I came up with the following layout that I think achieves a good balance. What do you think of this? If we think this works we can push it.

<img width="1392" alt="Screenshot 2019-12-09 at 09 45 53" src="https://user-images.githubusercontent.com/2250831/70420782-b8594300-1a68-11ea-96ec-6adef5b21a5c.png">

**Comment by Minenash** [comment]
That looks great! The only part missing is the view count next to the comment count

**Comment by RhettTrickett** [comment]
Okay, cool. Will add views, your article views will only be visible to you though. We want to keep vanity metrics private for now so as not to incentivise users in the wrong way.

**Comment by Minenash** [comment]
Make sense, will the same thing happen for Kudos/Likes (when they are added)? I see them abused on places like Twitter, but places like fanfiction.net doesn't have problems with it.

**Comment by RhettTrickett** [comment]
Okay, changes are up. I think we're leaning towards making upvotes public, as most platforms do. Haven't decided yet. It would be good to show something like this so that people can see there is a bit of a community while we're growing otherwise the platform may feel a bit empty relative to the engagement that you'd observe on other platforms. It's still up for discussion though.

**Comment by Minenash** [comment]
I fully agree (and maybe this should be another thread) the only disadvantage to likes but not views, is ratio. Is the low number of votes because not many people saw it, or because it isn't good. One thing we could do (though it wouldn't be as neat), is to add the like per view ratio in parenthesis. `↑ 5 likes (0.82)` It would make views public, but in a way that wouldn't insensitive making posts for views.
***
Now that I'm seeing it in action, I think it would look better without the word `read`, but I'm not sure if that would make it too confusing for users
***
Older posts don't sell to have the `X min read` on their feed cards, is this intentional?
***
_**Edit**: merged replies_

**Comment by Minenash** [comment]
Now that I'm seeing it in action, I think it would look better without the word `read`, but I'm not sure if that would make it too confusing for users

**Comment by Minenash** [comment]
Some older posts don't have the `X min` on their cards. Is this intentional?
