### ISSUE TITLE
Remove "duplicate" tags

### ISSUE THREAD

**Issue by Minenash** [able-bio/suggestion-box#35]
While I understand the nested nature of tags as explained [here](https://github.com/able-bio/suggestion-box/issues/8#issuecomment-518123364), I don't these should count:
* CSS, CSS 2.1, CSS 3
* HTML, HTML 4, HTML5
* ES4, ES5
I don't think there's many people out there that would want one and not the other, and if it's decided that they should remain split, I think the non-versiond one should be removed

**Comment by RhettTrickett** [comment]
Agreed, these are from an earlier experiment. Will start the process of removing them. They’re just attached to a few data objects so need to make sure they are removed safely.

**Comment by RhettTrickett** [comment]
These have now been removed, with the exception of the non-versioned CSS and HTML.
