### ISSUE TITLE
Editor not exlusively capturing Ctrl+K event

### ISSUE THREAD

**Issue by Minenash** [able-bio/suggestion-box#36]
Right now `Ctrl+K` is the shortcut to add a link; however, in Firefox it's the shortcut to do go to the address bar, add a `?` and do a web search. In editors like GitHub, if you do `Ctrl+K` it will still add the link, but _not_ activate Firefox's thing. However, in Able's editor, both Able's link adder, and Firefox's search thing activate.

**Comment by RhettTrickett** [comment]
Yep, I also get this. This is one for @drenther.

**Comment by drenther** [comment]
Will look into it.

**Comment by RhettTrickett** [comment]
This should be fixed now.
