### ISSUE TITLE
"Add a link" fails on valid single-letter domain

### ISSUE THREAD

**Issue by anson-vandoren** [able-bio/suggestion-box#39]
**Describe the bug**
The link dialog box does not recognize a valid URL if the domain is a single letter. The dialog works correctly if any random letter is added before or after the "t".

**To Reproduce**
1. Create a new post
2. Highlight any text and press Ctrl(Cmd)-K for the link dialog
3. Enter any valid URL that has a single character domain (e.g., [https://x.org](https://x.org), [https://t.me](https://t.me), [https://t.co](https://t.co))
4. See error message "Invalid URL! Make sure you start the link with http:// or https://"

**Expected behavior**
No error message, and the link is formed correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/4073391/71416302-aead0f00-2614-11ea-9f0a-7566668c6f98.png)

**Desktop (please complete the following information):**
 - Brave
 - macOS

**Additional context**
N/A

**Comment by drenther** [comment]
Will look into this. Thanks for reporting.

**Comment by RhettTrickett** [comment]
This should be fixed now.

**Comment by anson-vandoren** [comment]
Yup! Works fine for me now.
Thanks!
