### ISSUE TITLE
Add button for skill or portfolio 

### ISSUE THREAD

**Issue by mjablecnik** [able-bio/suggestion-box#4]
In my profile I see that I don't have any skill or Portfolio.
It should be nice when I will have some button for add my skills or Portfolio info there. 
Instead of text: `Martin has no skills yet.`
I don't know how can add it there now.

![screenshot from 2019-01-18 16-36-00](https://user-images.githubusercontent.com/2686906/51396539-88970900-1b3f-11e9-9cbf-8ebf44576ebf.png)

**Comment by RhettTrickett** [comment]
Yes, this should actually be hidden for now. Will address. We're wrapping up work on a major feature for skills where this area will then make more sense.

**Comment by RhettTrickett** [comment]
Okay, have now made a few changes here:

1. If you do not have any skills your profile will not show the skills tab. A new skills feature is coming soon which will allow you to earn skills for your profile.
2. If you click on your portfolio tab, you will now see a green button to add a project if you don't have any projects. You can also click the + icon in the top right corner next to your profile image to add more projects and other content to your profile.

I'm going to close this now as the new skills feature will allow you to add skills to your profile when it is ready.
