### ISSUE TITLE
Allow Configuring Behavior of ToC

### ISSUE THREAD

**Issue by zschuessler** [able-bio/suggestion-box#40]
**Describe the bug**
For a very long article with many headings, the table of contents in the left sidebar gets real wild.

I'd like to be able to configure it so that only the h1 headings are used, since the many h2/h3 headings are cluttering the ToC.

**To Reproduce**
1. Go to https://able.bio/zschuessler/design-challenge-congressional-vote-data--56ojdv7
2. Observe a WILD table of contents. very wild.

**Expected behavior**
Ability to say, "hey only show h1s there." I want to keep it there but have less vertical space.

**Desktop (please complete the following information):**
 - Chrome / Win10

**Additional context**
Thanks for making a Medium competitor. Enough people complained that I posted another article to Medium recently that I decided to switch. Cheers.

**Comment by zschuessler** [comment]
Sorry - I realize my pasting from Medium converted the headings to major headings. This looks much better with adding the small heading + using bold p tags as an h3. I'll close, this works!

**Comment by RhettTrickett** [comment]
Hey Zachary, welcome to Able! 

You’ve just reminded me that we still need to add the ability to toggle the ToC on/off. Will get that sorted in the next 2-3 weeks.
