### ISSUE TITLE
Sorting by topic only works when your feed sort is 'Feed'

### ISSUE THREAD

**Issue by Minenash** [able-bio/suggestion-box#41]
**Describe the bug**
You can filter posts by topic by clicking on the topic on the left side. However this only works when you're sorting your feed by `Feed` instead of `Latest` or `Popular`

**To Reproduce**
1. Sort by `Latest`
2. Click on a topic
3. View entries 

**Expected behavior**
For only posts that have the topic tags are included regardless of the feed sort

**Desktop (please complete the following information):**
 - Firefox, but I doubt it matters

**Comment by RhettTrickett** [comment]
I’ve pushed a fix, so this should work now. Could you check and confirm that it’s working as expected?

**Comment by Minenash** [comment]
Yup looks like it works, thanks!
