### ISSUE TITLE
Current tag system is too limiting

### ISSUE THREAD

**Issue by jmiskovic** [able-bio/suggestion-box#45]
The list of allowed tags leaves a lot to be desired. They cover mostly programming languages, with couple platforms added in randomly. Not everyone interests are covered there. Because of bad tag coverage it feels like some IT topics are not considered welcome on the platform.

Apart from just list of technologies, I would like to see tags for domains. For instance, graphics, audio, security, embedded, bio-informatics, machine learning and so on. People interested in those domains would likely like to read any relevant article regardless of technology used.

The easy solution is to allow writers to attach any tag to their articles. Top used tags would be presented to readers. Even if moderation of tag list is desired/necessary, writers should still be able to use any tags when writing articles, but only vetted tags would be visible on published article.

Minor issue: OOP is listed twice in tags list.

**Comment by RhettTrickett** [comment]
Hi @jmiskovic. Yes, fully agree with you. We're actually working on implementing what you've suggested at the moment as part of finishing up a _big_ upgrade to the editor. This should be available in the next few days. I'll update you here when this is available.

In the meantime I'll remove that OOP dupe, thanks for raising that.

**Comment by RhettTrickett** [comment]
Hi @jmiskovic - we've now released our updated editor which allows you to create tags. Feel free to create the tags you like and we'll moderate them as necessary.

You can read more details about the release here: https://able.bio/rhett/improving-our-data-portability-and-markdown-editor--e8b996bc
