### ISSUE TITLE
Import fails if file contains code block in a language not recognized by the highlighter

### ISSUE THREAD

**Issue by clartaq** [able-bio/suggestion-box#46]
**Describe the bug**
If you attempt to drag a Markdown file that contains a fenced code block written in a language not recognized by the highlighter, the import fails.

**To Reproduce**
1. Drag a Markdown containing a block of code written in Clojure/ClojureScript/EDN to the editor demo page.'
4. The import will fail.

**Expected behavior**
I expected the import to succeed. If the language is not recognized, it should at least succeed and highlight the code block as "plain".

**Desktop (please complete the following information):**
 - Browser - Safari (probably others)
 - macOS 10.15.5

**Additional context**
The fallback for the highlighter should be "plain", but it would be nice if you expanded the "known" languages. In my case, Clojure, ClojureScript, EDN, Lisp, Scheme, Racket would be nice.

**Comment by RhettTrickett** [comment]
Thanks for reporting @clartaq - we are aware of this. @drenther is working on a fix.

**Comment by RhettTrickett** [comment]
Hi @clartaq - this has now been fixed.
