### ISSUE TITLE
Import Front Matter in Additional Markup Languages

### ISSUE THREAD

**Issue by clartaq** [able-bio/suggestion-box#47]
**Describe the bug**
When a Markdown file has front matter in a language other than YAML, it fails.

**To Reproduce**
1. Drag a Markdown file containing front matter in TOML onto the editor.
4. Import fails

**Expected behavior**
Accept and parse the front matter and proceed with import.

**Desktop (please complete the following information):**
 - Browser - Safari, probably others
 - macOS 10.15.5

**Additional context**
Front matter markup in additional languages would be nice. YAML is fine, TOML is better IMHO. Maybe JSON too. Since Hugo (what I use for my own blog) accepts TOML, that's what I use now. (I used to use YAML too.)

**Comment by RhettTrickett** [comment]
Hi @clartaq - @drenther has now added support for parsing TOML and JSON. These fields need to be fenced within in --- or +++
