### ISSUE TITLE
Article editor is very poor

### ISSUE THREAD

**Issue by mjablecnik** [able-bio/suggestion-box#5]
When I want add some article https://able.bio/articles/add   I see very blank page:
![screenshot from 2019-01-18 16-44-21](https://user-images.githubusercontent.com/2686906/51397046-a749cf80-1b40-11e9-89ed-a3e4025ffe99.png)

Where is not Any panel for format my text, add picture, tables or links and another things like in
the add project: https://able.bio/project/add 

![screenshot from 2019-01-18 16-44-31](https://user-images.githubusercontent.com/2686906/51397270-2212ea80-1b41-11e9-8768-942de8ea444b.png)

I would like have the same or similar editor for adding articles like for adding projects.

**Comment by RhettTrickett** [comment]
When writing articles, if you highlight any of the body text you've written you should be presented with a Medium style formatting bar.

I plan to put a lot of energy into the article composer soon. Just finishing up another major feature on Able that's been taking quite a bit of work to finalise.

**Comment by RhettTrickett** [comment]
Planning to build a new article composer using https://www.slatejs.org/ 

Have added this to that milestone.

**Comment by RhettTrickett** [comment]
Hey @Applemann - Long time! Just to let you know we've launched the first version of our new editor. Log in and check it out at https://able.bio/new
