### ISSUE TITLE
Adding new tags clears existing tags

### ISSUE THREAD

**Issue by kerrishotts** [able-bio/suggestion-box#51]
**Describe the bug**
When I add a new tag, the existing tags in the list are cleared

**To Reproduce**
1. Write a post (or edit one)
2. Enable tags
3. Add an existing tag like "JavaScript"
4. Add a NEW tag

The tag list only includes the NEW tag.

**Expected behavior**
Both existing and new tag should be in the tag list.

**Desktop (please complete the following information):**
 - Safari
 - macOS 10.15.5

**Comment by drenther** [comment]
Thanks for the detailed report. Will look into it.

**Comment by RhettTrickett** [comment]
This should be fixed now.
