### ISSUE TITLE
Dates are yearless

### ISSUE THREAD

**Issue by Minenash** [able-bio/suggestion-box#53]
**Describe the bug**
Dates on the main page don't include the year for posts that are over a year old.

**To Reproduce**
1. Go to the main page -> popular
2. See that the dates don't have a year, despite being 2½ years old

**Comment by drenther** [comment]
hey thanks @Minenash - you're right! Good catch.

@RhettTrickett Can you take a look?

**Comment by RhettTrickett** [comment]
Thanks @Minenash - this has been fixed. You should now see the year for articles that were not published in the current year.

**Comment by Minenash** [comment]
The same problem also exists on profile pages

**Comment by drenther** [comment]
Noted. Thanks @Minenash we will push a fix soon

**Comment by RhettTrickett** [comment]
Have fixed profile pages now.
