### ISSUE TITLE
Duplicated posts

### ISSUE THREAD

**Issue by sudoaza** [able-bio/suggestion-box#56]
**Describe the bug**
When I go to create a post, when I save, each time creates a new post.

**To Reproduce**
1. Go to create a new post
2. Click on Markdown Mode
3. Click on the side bar and enable subtitle, series, topics (I suspect it's the series the issue but not sure)
4. Save it
5. Modify and save again
6. Try to leave the page, it should warn you about leaving
7. Go to your post index
8. See error

**Expected behavior**
Should save only one post (still better than 0 post though :) )

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Firefox with uBlock origin enabled 
 - Linux

**Additional context**
After going away and coming back to edit it doesn't create more duplicates.

**Comment by drenther** [comment]
Thanks for reporting. We will look into it. @RhettTrickett FYI

**Comment by RhettTrickett** [comment]
Yes, sorry. Am aware and working on this.

**Comment by RhettTrickett** [comment]
Took a second look and think I found the problem. Should be fixed now.

**Comment by sudoaza** [comment]
Confirm, I created a new one and didn't happen.
