### ISSUE TITLE
Save my interests

### ISSUE THREAD

**Issue by mjablecnik** [able-bio/suggestion-box#6]
I think that should be very useful when in the profile settings will be some form for save of my interesting technology.
For example:
I am interested in Linux, Python, Java, Kotlin, Cloud technology
And when will have some new Article about it so this article will be displayed  on the https://able.bio/ page where I can find it and read.

But I am not interested in HTML, CSS, Javascript
so I hope that it not will be showed on the first positions there.

**Comment by RhettTrickett** [comment]
100% agree. You specify your interests on sign-up for this exact purpose. I still need to implement the following though:

- Newsfeed algorithm to prioritise articles by interest.
- Interface to manage interests
- Digest email to send weekly / daily email alert of new articles that match interests.

**Comment by RhettTrickett** [comment]
You can now edit your interests here: https://able.bio/settings/interests
