### ISSUE TITLE
Add header image doesn't work

### ISSUE THREAD

**Issue by ZoranPandovski** [able-bio/suggestion-box#7]
**Describe the bug**
500 error is thrown when I try to add a header image to an article.

**To Reproduce**
1. Go to add a header image
2. Select image (in my case jpg format)
3. 500 error is thrown

**Desktop (please complete the following information):**
 - Chrome browser

**Additional context**
After a few attemps, the image was uploaded.

**Comment by RhettTrickett** [comment]
Hey @ZoranPandovski - thanks for raising this!

I reviewed the log for this error and have pushed a patch that should fix the offending code. Have tested and all seems fine now.

Would you mind confirming all is working on your side when you have a moment?

**Comment by ZoranPandovski** [comment]
I just checked and it works great. Thanks, @RhettTrickett .
