### ISSUE TITLE
Delete article throws error

### ISSUE THREAD

**Issue by ZoranPandovski** [able-bio/suggestion-box#9]
**Describe the bug**
Delete article option is not working. Server Error 500 is thrown when deleting an article.
Note that the article contains only the Title.

**To Reproduce**
1. Create a new article
2. Delete it

**Expected behavior**
The article should be deleted.

**Comment by RhettTrickett** [comment]
Thanks Zoran!

This should be fixed now. Could you test and confirm on your side?

**Comment by ZoranPandovski** [comment]
Yes, now it's working. Thanks
